name: Pokemine
main: at.jojokobi.pokemine.PokeminePlugin
version: 0.1
author: jojokobi
load: STARTUP
api-version: 1.17
depend: [JojokobiUtil]
commands: 
  pokemine:
    description: This command spawns pokemon
    usage: /pokemine <pokemon> [level]
  fixedgyms:
    description: This generates the 18 standard gyms around the spawn
    usage: /fixedgyms